
exclude: ['README.md', 'params.json']

permalink: /:categories/:title

excerpt_separator: "<!-- more -->"

# Custom variables (available through {% site.KEY %})
domain: demoive.github.io

disqus:
	shortname: demoive-github

google:
	analytics:
		id: UA-2390640-8
