
exclude: ['README.md', 'params.json']

permalink: /:categories/:title

excerpt_separator: "<!-- more -->"

# Custom variables (available through {% site.KEY %})
domain: demoive.github.io

sitemap:
  changefreq: monthly
#    archive-threshold-days: 60
    
disqus:
  shortname: demoive-github

google:
  analytics:
    id: UA-2390640-8
